List content = [
  [
    "https://i.pravatar.cc/300",
    "Jam",
    "Web developer | Android developer",
    "20m",
    "My professinal desk for work",
    "https://picsum.photos/id/2/500/300",
    "likes 20",
    "5 comments . ",
    "2 shares",
  ],
  [
    "https://i.pravatar.cc/400",
    "Tom",
    "Flutter Developer",
    "5h",
    "This is my new post check it out",
    "https://picsum.photos/id/3/500/300",
    "likes 500",
    "64 comments . ",
    "16 shares",
  ],
  [
    "https://i.pravatar.cc/100",
    "Panther",
    "Flutter Developer | Android Developer",
    "3h",
    "Hope you guys like my content",
    "https://picsum.photos/id/4/500/300",
    "likes 250",
    "10 comments . ",
    "4 shares",
  ],
  [
    "https://i.pravatar.cc/500",
    "Jimmy",
    "Java Developer | Django Developer",
    "5h",
    "This is my new post check it out",
    "https://picsum.photos/id/5/500/300",
    "likes 99",
    "3 comments . ",
    "0 shares",
  ],
];
